user_password: ENC[AES256_GCM,data:VUJzawIPsJk=,iv:ArSXR+teg7ARfKpZ4niZoPIA03L2lHmM2Xr1wk4hzAI=,tag:YSjgB2h4F4Bww2SDbrahDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13x4npk4kkd485pp22xd52u2ddvvgx8x8lz6zwqr0vemkz4da9a5szs6z67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVXlLb2pXSEV4Ny9ob0hK
            bnhaVmxlbTgwN3ZzZUN2SjBkcklQekgyOVFVClhFS050aXM1bkhuK0I3aUF5eVNp
            cnJNR1M1UEtQeVFaZ21FYytBbUFqQ3cKLS0tIGh2blYzNnNKVEN5NVRKenJwcW9F
            azZDd0NqbEl3T29nOFhyUGNVeHhjYzgK4IUaokAGOF6MqumLpZYHBC/atT8orXPf
            uTb+ihmakCMdPnMohWrhDC0C09FO+oZEjfomSuuOHI4Gsoyc1p+5Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T18:23:38Z"
    mac: ENC[AES256_GCM,data:qdlI94JDJyAG6Jz8Odfamu6mGPwfpEPuARfAQPy0cyQrmKe0nz74MrubTMBlbDqjS6zFxLQ4JdubFmIy9YA3tTJBBREyVujZYeWfjPvtQrQaDyDu42+0vmZuXrMX79k59rNy2g0EJ/2S5QyF6cFAFWWelZHSQi/mW5qSuujgsSQ=,iv:M3TChMeO6MDlpfRT+iN9x6w3EMeD0XCu8ovD5quOidQ=,tag:oCSPkxC3rN/VRjHMjU2nPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
